spring:
  application:
    name: my-organisation
  ###
  #   Database Settings
  ###
  datasource:
  #<------H2-------------->
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/my-organisation_db;DB_CLOSE_ON_EXIT=FALSE; #AUTO_SERVER=TRUE

    #password:   #h2
  #<----------End H2----------->

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

  ##############################################
  #   H2
  ###
  h2:
    console:
      enabled: true
      path: /h2

##############################################

server:
  port: 8082